### PR TITLE
fix #63

### LINKED ISSUE #63: Broken with dmd-nigthly
https://github.com/dlang/dmd/pull/6839 fixed some holes in the safety system. Unfortunately D-YAML is affected:

```
source/dyaml/emitter.d(614,20): Error: address of variable this assigned to this with longer lifetime
source/dyaml/emitter.d(639,20): Error: address of variable this assigned to this with longer lifetime
```

For the next days I am a bit low on time, so if anyone has time to prepare fix, please go for it ;-)

### PR DESCRIPTION
**Pull request by BBasile**
`.funcptr` is always good, so only forces the context before usage.
The supplemental assignation is cheap (delegate are value-types and stuff to assign is of CPU registry size), though `Emitter` is necessarily _slightly_ slower than before.

### CODE REVIEW

File: source/dyaml/emitter.d [hunk 1]
```diff
@@ -73,6 +73,12 @@ private alias canFind = std.algorithm.canFind;
 //Emits YAML events into a file/stream.
 struct Emitter 
 {
+
+    // disable moves /copy b/c state_ carries original this context
+    @disable this(this);
```
Comment (BBasile) [inline source/dyaml/emitter.d]: Possible breakage in user code. But without this i cant see how to trust the two methods
